" Ruoyan Wong's vimrc
"
" Use Vim defaults instead of 100% vi compatibility 
set nocompatible

"""""""""""""""""""""""""""""""""""""""
"        General Settings 
"                 
"""""""""""""""""""""""""""""""""""""""

if has("gui_running")
    set background=dark
    colorscheme solarized
else
    " colorscheme vibrantink
    colorscheme molokai
    let g:molokai_original = 0
endif

set number          " Display line number
set incsearch       " Incremental search 
set ignorecase      " Ignore case
set confirm         " 
set history=50      " Keep 50 lines of command line history
set showcmd         " Display incomplete commands
set autoread        " Auto read when file is changed from outside
set showmatch       " Show matching bracets when text indicator is over them
set novisualbell    " No sound on errors
syntax enable       " Syntax highlight
set cursorline      " Cursor current line
set encoding=utf-8  " Set default-encoding to utf-8
let mapleader=","

" Set tab setting
set smarttab
set expandtab
set shiftwidth=4
set tabstop=4

" Indent setting
set autoindent                     " Auto indent
set smartindent                    " Smart indent 
set cindent                        " C/C++ indent style

" Disable bakup and swap file
set nobackup
set noswapfile
set nowritebackup

" Enable fold and space key to switch fold
set foldenable
set foldmethod=manual
nnoremap @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')

" Set ststusline
set laststatus=2
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}

" Backspace and cursor keys wrap to previous/next line
set backspace=indent,eol,start 
set whichwrap+=<,>,[,]

" Map auto complete of (, ", ', [

" Alias config 

iab ryw Ruoyan Wong
iab wry wangruoyan@snda.com
iab ggg kid.xiyang@gmail.com

" 通过模板创建文件
" autocmd BufNewFile *.py 0r ~/.vim/template/py_template.py
" autocmd BufNewFile *.sh 0r ~/.vim/template/bash_template.py

"""""""""""""""""""""""""""""""""""""""
"       Addons Configuration
"                 
"""""""""""""""""""""""""""""""""""""""

" pathogen.vim
" https://github.com/tpope/vim-pathogen
"
call pathogen#infect('stuff')
filetype plugin on
filetype indent on

" template_loader.vim
"
let g:template_load = 1
let g:template_tags_replacing = 1
let g:T_AUTHOR = "Ruoyan Wong"
let g:T_DATE_FORMAT = "%Y年%m月%d日"

" vim-colors-solarized.vim
" https://github.com/altercation/solarized/tree/master/vim-colors-solarized
"

" cs-explorer.vim
" http://www.vim.org/scripts/script.php?script_id=1298
nmap <leader>cs :ColorSchemeExplorer<CR>

" indent-guides.vim
" http://www.vim.org/scripts/script.php?script_id=3361
let g:indent_guides_auto_colors = 1
let g:indent_guides_enable_on_vim_startup = 0
nmap <leader>ig :IndentGuidesToggle<CR>

" nerd-tree.vim
" http://www.vim.org/scripts/script.php?script_id=1658
nmap <leader>nt :NERDTreeToggle<CR>
