ZSH=$HOME/.zsh

# add a function path
fpath=($ZSH/functions $ZSH/completions $fpath)

# Load all of the config files in lib directory that end in .zsh
for config_file ($ZSH/lib/*.zsh) source $config_file

# Load and run compinit
autoload -U compinit
compinit -i

ZSH_THEME="saipanno"
if [ "$ZSH_THEME" = "random" ];then
    themes=($ZSH/themes/*.theme)
    N=${#themes[@]}
    ((N=(RANDOM%N)+1))
    RANDOM_THEME=${themes[$N]}
    source "$RANDOM_THEME"
    echo "Random theme '$RANDOM_THEME' loaded..."
else
    source "$ZSH/themes/$ZSH_THEME.theme"
fi
